// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxDatabase;

namespace TaxDatabase.Migrations
{
    [DbContext(typeof(DatabaseRepository))]
    partial class DatabaseRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("TaxStore.Dto.MunicipalityData", b =>
                {
                    b.Property<string>("MunicipalityID")
                        .HasColumnType("TEXT");

                    b.HasKey("MunicipalityID");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("TaxStore.Dto.TaxData", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MunicipalityDataID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TaxValue")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("MunicipalityDataID");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("TaxStore.Dto.TaxData", b =>
                {
                    b.HasOne("TaxStore.Dto.MunicipalityData", null)
                        .WithMany("TaxSchedules")
                        .HasForeignKey("MunicipalityDataID");
                });
#pragma warning restore 612, 618
        }
    }
}
